version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=2000
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '2000:2000'
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
